ALTER TABLE students CHANGE father_pic father_pic VARCHAR(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE mother_pic mother_pic VARCHAR(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE guardian_pic guardian_pic VARCHAR(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE height height VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE weight weight VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE measurement_date measurement_date VARCHAR(200) NULL DEFAULT NULL, CHANGE dis_reason dis_reason VARCHAR(200) NULL DEFAULT NULL, CHANGE dis_note dis_note VARCHAR(200) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL;


ALTER TABLE students CHANGE parent_id parent_id VARCHAR(225) NULL DEFAULT NULL;


ALTER TABLE students CHANGE route_id route_id VARCHAR(225) NULL DEFAULT NULL, CHANGE school_house_id school_house_id VARCHAR(225) NULL DEFAULT NULL, CHANGE blood_group blood_group VARCHAR(225) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE vehroute_id vehroute_id VARCHAR(225) NULL DEFAULT NULL, CHANGE hostel_room_id hostel_room_id VARCHAR(225) NULL DEFAULT NULL, CHANGE guardian_is guardian_is VARCHAR(225) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE guardian_occupation guardian_occupation VARCHAR(225) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE disable_at disable_at VARCHAR(225) NULL DEFAULT NULL;



ALTER TABLE sch_settings CHANGE languages languages VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE date_format date_format VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE time_format time_format VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE currency currency VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE currency_symbol currency_symbol VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE cron_secret_key cron_secret_key VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE class_teacher class_teacher VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE start_month start_month VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE admin_logo admin_logo VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE admin_small_logo admin_small_logo VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE adm_start_from adm_start_from VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE staffid_start_from staffid_start_from VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE online_admission_payment online_admission_payment VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE online_admission_amount online_admission_amount VARCHAR(255) NULL DEFAULT NULL, CHANGE online_admission_instruction online_admission_instruction TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE online_admission_conditions online_admission_conditions TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE category category VARCHAR(255) NULL DEFAULT NULL, CHANGE lastname lastname VARCHAR(255) NULL DEFAULT NULL, CHANGE guardian_name guardian_name VARCHAR(255) NULL DEFAULT NULL, CHANGE guardian_phone guardian_phone VARCHAR(255) NULL DEFAULT NULL, CHANGE guardian_occupation guardian_occupation VARCHAR(255) NULL DEFAULT NULL, CHANGE ifsc_code ifsc_code VARCHAR(255) NULL DEFAULT NULL, CHANGE bank_name bank_name VARCHAR(255) NULL DEFAULT NULL, CHANGE mobile_api_url mobile_api_url VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE start_week start_week VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE my_question my_question VARCHAR(255) NULL DEFAULT NULL;


ALTER TABLE students CHANGE image image TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL;


ALTER TABLE item CHANGE description description TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL;


ALTER TABLE certificates CHANGE certificate_text certificate_text TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE left_header left_header TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE center_header center_header TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE right_header right_header TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE left_footer left_footer TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE right_footer right_footer TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE center_footer center_footer TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE background_image background_image VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE status status TINYINT(1) NULL DEFAULT NULL, CHANGE header_height header_height INT NULL DEFAULT NULL, CHANGE content_height content_height INT NULL DEFAULT NULL, CHANGE footer_height footer_height INT NULL DEFAULT NULL, CHANGE content_width content_width INT NULL DEFAULT NULL, CHANGE enable_student_image enable_student_image TINYINT(1) NULL DEFAULT NULL COMMENT '0=no,1=yes', CHANGE enable_image_height enable_image_height INT NULL DEFAULT NULL;



ALTER TABLE certificates CHANGE left_header left_header TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL, CHANGE center_header center_header TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL, CHANGE right_header right_header TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL, CHANGE left_footer left_footer TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL, CHANGE right_footer right_footer TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL, CHANGE center_footer center_footer TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL;


ALTER TABLE mlms_users CHANGE is_student is_student INT NULL DEFAULT NULL, CHANGE is_instructor is_instructor INT NULL DEFAULT NULL, CHANGE username username VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE password password VARCHAR(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE lostpw lostpw VARCHAR(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE new_email new_email VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE new_email_key new_email_key VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE new_password_key new_password_key VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE new_password_requested new_password_requested DATETIME NULL DEFAULT NULL, CHANGE name name VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE designation designation VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE prof_info prof_info TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE images images VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE website website VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE blog blog VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE facebook facebook VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE twitter twitter VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE show_email show_email TINYINT(1) NULL DEFAULT NULL, CHANGE show_website show_website TINYINT(1) NULL DEFAULT NULL, CHANGE show_blog show_blog TINYINT(1) NULL DEFAULT NULL, CHANGE show_facebook show_facebook TINYINT(1) NULL DEFAULT NULL, CHANGE show_twitter show_twitter TINYINT(1) NULL DEFAULT NULL, CHANGE author_title author_title VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE created_at created_at DATETIME NULL DEFAULT NULL, CHANGE register_time register_time INT NULL DEFAULT NULL, CHANGE ip_address ip_address VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE webstatus webstatus VARCHAR(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NULL DEFAULT NULL, CHANGE created_by created_by INT NULL DEFAULT NULL, CHANGE group_id group_id INT NULL DEFAULT NULL, CHANGE department department INT NULL DEFAULT NULL, CHANGE last_login last_login DATETIME NULL DEFAULT NULL, CHANGE first_time_login first_time_login INT NULL DEFAULT NULL, CHANGE demorecords demorecords INT NULL DEFAULT NULL;


ALTER TABLE mlms_student_exam_report CHANGE stud_id stud_id VARCHAR(255) NULL DEFAULT NULL, CHANGE exam_id exam_id VARCHAR(255) NULL DEFAULT NULL, CHANGE pro_id pro_id VARCHAR(255) NULL DEFAULT NULL, CHANGE attempt_no attempt_no VARCHAR(255) NULL DEFAULT NULL, CHANGE obtain_marks obtain_marks VARCHAR(255) NULL DEFAULT NULL, CHANGE tot_marks tot_marks VARCHAR(255) NULL DEFAULT NULL


ALTER TABLE mlms_exam_paper CHANGE exam_title exam_title VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE description description VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE exam_type exam_type VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE published published VARCHAR(255) NULL DEFAULT NULL, CHANGE total_marks total_marks VARCHAR(255) NULL DEFAULT NULL, CHANGE instructions instructions VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE passing_score passing_score VARCHAR(255) NULL DEFAULT NULL, CHANGE pass_feedback pass_feedback VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE fail_feedback fail_feedback VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE view_score_realtime view_score_realtime VARCHAR(255) NULL DEFAULT NULL, CHANGE order_type order_type VARCHAR(255) NULL DEFAULT NULL, CHANGE skip skip VARCHAR(255) NULL DEFAULT NULL, CHANGE retake retake VARCHAR(255) NULL DEFAULT NULL, CHANGE attempt_limit attempt_limit VARCHAR(255) NULL DEFAULT NULL, CHANGE time_limit_b time_limit_b VARCHAR(255) NULL DEFAULT NULL, CHANGE duration_h duration_h VARCHAR(255) NULL DEFAULT NULL, CHANGE duration_m duration_m VARCHAR(255) NULL DEFAULT NULL, CHANGE wait_b wait_b VARCHAR(255) NULL DEFAULT NULL, CHANGE wait_w wait_w VARCHAR(255) NULL DEFAULT NULL, CHANGE wait_d wait_d VARCHAR(255) NULL DEFAULT NULL, CHANGE wait_h wait_h VARCHAR(255) NULL DEFAULT NULL, CHANGE wait_m wait_m VARCHAR(255) NULL DEFAULT NULL, CHANGE see_result see_result VARCHAR(255) NULL DEFAULT NULL, CHANGE show_right_answers show_right_answers VARCHAR(255) NULL DEFAULT NULL, CHANGE created_by created_by VARCHAR(255) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL, CHANGE exam_category exam_category VARCHAR(255) NULL DEFAULT NULL;


ALTER TABLE mlms_usertrash CHANGE lostpw lostpw VARCHAR(256) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE email email VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE designation designation VARCHAR(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE images images VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE full_bio full_bio TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE website website VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE blog blog VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE facebook facebook VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE twitter twitter VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE author_title author_title VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE trash trash INT NULL, CHANGE ip_address ip_address VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL;


ALTER TABLE mlms_users CHANGE prof_info prof_info TEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE emaillink emaillink LONGTEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE website website VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE blog blog VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE facebook facebook VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE twitter twitter VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE show_email show_email TINYINT(1) NULL, CHANGE show_website show_website TINYINT(1) NULL, CHANGE show_blog show_blog TINYINT(1) NULL, CHANGE show_facebook show_facebook TINYINT(1) NULL, CHANGE show_twitter show_twitter TINYINT(1) NULL, CHANGE author_title author_title VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE trash trash INT NULL, CHANGE register_time register_time INT NULL, CHANGE ip_address ip_address VARCHAR(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE webstatus webstatus VARCHAR(20) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL, CHANGE created_by created_by INT NULL, CHANGE group_id group_id INT NULL, CHANGE department department INT NULL, CHANGE first_time_login first_time_login INT NULL, CHANGE demorecords demorecords INT NULL, CHANGE referral_code referral_code VARCHAR(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL;
