<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Students extends Model
{
    use HasFactory;
    protected $fillable = [
        'id',
        'parent_id',
'admission_no',
'roll_no',
'admission_date',
'firstname',
'middlename',
'lastname',
'rte',
'image',
'mobileno',
'email',
'state',
'city',
'pincode',
'religion',
'cast',
'dob',
'gender',
'current_address',
'permanent_address',
'category_id',
'route_id',
'school_house_id',
'blood_group',
'vehroute_id',
'hostel_room_id',
'adhar_no',
'samagra_id',
'bank_account_no',
'bank_name',
'ifsc_code',
'guardian_is',
'father_name',
'father_phone',
'father_occupation',
'mother_name',
'mother_phone',
'mother_occupation',
'guardian_name',
'guardian_relation',
'guardian_phone',
'guardian_occupation',
'guardian_address',
'guardian_email',
'father_pic',
'mother_pic',
'guardian_pic',
'is_active',
'previous_school',
'height',
'weight',
'measurement_date',
'dis_reason',
'note',
'dis_note',
'app_key',
'parent_app_key',
'disable_at',
    ];
}
